name: "build project and push to release branch"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run build command
        run: |
          npm ci
          npm run build
          ls
          git branch
